<?php
namespace App\States\Kebbi;

trait Zuru

{
	public function zuru()
	{
		return [
            [
            	'district'=>'Bedi','towns'=>
            	[
            		'Bedi',
					'Danko',
					'Domo',
					'Dongo',
					'Gwanfi',
					'Kele',
					'Kendu',
					'Koga',
					'Kyabu',
					'Landi',
					'Maraban Dako',
					'Marafa',
					'Sanforo (Filin-Jirgi)',
					'Shindi',
					'T/Maga',
					'Unguwan Gara',
					'Unguwan Joji',
					'Unguwan Kate Ubandawaki',
					'Unguwan Kwanchi Manga',
					'Unguwan Rimi',
					'Unguwan Zuttu',
					'Unguwar Bagna',
					'Unguwar Kobo',
					'Yelmo'
            	]
            ],
            [
            	'district'=>'Dabai','towns'=>
            	[
            		'Banto Wuya',
					'Barshi Gademe',
					'Bijizo',
					'Chiroma',
					'D’Benzo',
					'D’oh',
					'Dabai',
					'Dabai Same',
					'Dago',
					'Damba',
					'Gamji',
					'Gangara',
					'Garbadu',
					'Gatawa',
					'Gogadi',
					'Gommawa',
					'Gwaram',
					'Isgogo',
					'Jangebe',
					'Kagara',
					'Kahe',
					'Kalgo',
					'Kezge',
					'Klanko',
					'Kseva',
					'Kurawa',
					'Kwendo',
					'Lajinga',
					'Makuwana',
					'Manga',
					'Marai',
					'Matsgi',
					'Msune',
					'Rumu',
					'Ruwan Bore',
					'Ruwan Gizo',
					'Ruwan Gora',
					'Sabon Birni',
					'Sabon Garin Dabai',
					'Seam Saune',
					'Senchi',
					'Sh/Galadima',
					'Sh/Kayaya',
					'Tara',
					'Ukau',
					'Ung. Lalle',
					'Ushe',
					'Zom Zomo'
            	]
            ],
            [
            	'district'=>'Isgogo/Dago','towns'=>
            	[
					'Dago Gari',
					'Dago Karkari',
					'Idgobo',
					'Jambo',
					'Jondo Tuta',
					'Kdumti',
					'Komi Semna',
					'Riatu',
					'Semchlali',
					'Semgongo',
					'Tota',
					'Uhu',
					'Unguwan Galadima',
					'Utmu',
					'Wheleta',
					'Yadi',
					'Zangina'
            	]
            ],
            [
            	'district'=>'Manga Ushe','towns'=>
            	[
					'Adai',
					'Adkwnh',
					'Ahdgoga',
					'Bili',
					'D/ Kolo',
					'Dankan- Kambari',
					'Dirin Daji',
					'Dirin Gari',
					'Dokan Hausawa',
					'Domo Garu',
					'Dongo Manga',
					'Dorowa',
					'Elembelu',
					'Gelwasa',
					'Ghazi',
					'Jan Binni',
					'Jan Dutsi',
					'Jigawa',
					'K/ Hodo',
					'Kaiwar Kasa',
					'Kaiwar Sama',
					'Knata',
					'Kogo',
					'Ma-essah',
					'Madugwa',
					'Magami',
					'Mahuta',
					'Makuku',
					'Mogoro',
					'Niger',
					'Rio',
					'Sakaba',
					'Sembren Manga',
					'Tunga Gwamna',
					'Udun Kudu',
					'Unguwan Raku',
					'Unguwan S/Usara',
					'Unguwan S/Ushe',
					'Usi',
					'WH-Kwebe'
            	]
            ],
            [
            	'district'=>'Rafin Zuru','towns'=>
            	[
					'Ayu',
					'Bagida',
					'Bakin Kasuwa',
					'Bena',
					'D/ Kibiya',
					'D/ Umaru',
					'Denkre',
					'Doga',
					'Dutsen Kwana',
					'Gwazawa',
					'Hedengen',
					'Jarkasa',
					'K’bancho',
					'Kango',
					'Kanya',
					'Machika',
					'Morai',
					'Passo',
					'Rade',
					'Rambo',
					'Riba Susu',
					'Rimi',
					'Sarku',
					'Semch Loli',
					'Shengel',
					'Somdoro',
					'Susu',
					'Tashar Rimi',
					'Unashi',
					'Wadako',
					'Waje',
					'Wasagu',
					'Yar Ali',
					'Yarkuka',
					'Zuttu'
            	]
            ],
            [
            	'district'=>'Rikoto','towns'=>
            	[
					'Bakin Tsauni',
					'Galadima',
					'Mangori',
					'Rikoto Fada',
					'Sabon Garin Rikoto',
					'Sabon Tasha',
					'Tudun Wada',
					'Unguwan Doro',
					'Unguwan Galadima',
					'Unguwan Henso',
					'Unguwan Nagoro',
					'Unguwan Yan Biyu'
            	]
            ],
		];
	}
}