<?php

namespace Modules\Health\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;
use Modules\Health\Entities\Treatment;

class TreatementTableSeederTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Model::unguard();

        $treatments = [
            'Abscopal effect',
            'Aguamiel',
            'Alglucosidase alfa',
            'Alternative uses for placenta',
            'Anthrax immune globulin',
            'Antiseptic lavage',
            'Apheresis',
            'Aquablation therapy',
            'Aquapheresis',
            'Arthrocentesis',
            'Athletic taping',
            'BaleDoneen Method',
            'Banding (medical)',
            'Bathroom privileges',
            'Bcr-Abl tyrosine-kinase inhibitor',
            'Bed rest',
            'Bioartificial liver device',
            'Bloodletting',
            'Carbonated soda treatment of phytobezoars',
            'Catholicon (electuary)',
            'Cauterization',
            'Celacade',
            "Cell-based therapies for Parkinson's disease",
            'Chemoprophylaxis',
            'Chest wall oscillation',
            'Chondroprotection',
            "Chronotherapy (sleep phase)",
            'CLaCS',
            'Clinical uses of mesenchymal stem cells',
            'Combination therapy',
            'Comedo extraction',
            'Cranial electrotherapy stimulation',
            'Craterization',
            'Culdoscopy',
            'Cyanoacrylate',
            'Debridement',
            'Demand valve oxygen therapy',
            'Magnesium and depression',
            'Dermabrasion',
            'Diaphragm pacing',
            'Directly observed treatment, short-course',
            'Dopamine therapy',
            'Drug of last resort',
            'Dry-powder inhaler',
            'Ebola virus disease treatment research',
            'EBOO',
            'Electrical muscle stimulation',
            'Electroanalgesia',
            'Electronic prescribing',
            'Electrotherapeutics',
            'Electrotherapy',
            'Endoscopic nasopharyngectomy',
            'Enzyme replacement therapy',
            'Epidural steroid injection',
            'Expiratory apnea',
            'Extracorporeal shockwave therapy',
            'Facet joint injection',
            'Flea treatments',
            'Fluid replacement',
            'Frenkel exercises',
            'Gene therapy for osteoarthritis',
            'Glossopharyngeal breathing',
            'Graded exercise therapy',
            'Growth attenuation',
            'Harris flush',
            'Heating pad',
            'Heliox',
            'Hepatitis B immune globulin',
            'Heptavalent botulism antitoxin',
            'Heroic measure',
            'High-dose estrogen',
            'Hormone therapy',
            'Hot water bottle',
            'Hydrodilatation',
            'Hydrogel dressing',
            'Hydrogogue',
            'Hyperbaric medicine',
            'Hyperbaric treatment schedules',
            'Hyperimmune globulin',
            'Hypnosis',
            'Hypnotherapy',
            'Hypodermoclysis',
            'Hypothermia therapy for neonatal encephalopathy',
            'Ice pack',
            'Immunoglobulin therapy',
            'Immunosuppression',
            'Injection lipolysis',
            'Intermittent hypoxia',
            'Intermittent vacuum therapy',
            'Interprofessional education',
            'Interventionism (medicine)',
            'Intracerebroventricular injection',
            'Intramuscular injection',
            'Intraosseous infusion',
            'Intraperitoneal injection',
            'Intrathecal administration',
            'Intravenous therapy',
            'Intravitreal administration',
            'Isocentric technique',
            'Kraamzorg',
            'Laparoscopy',
            'Laser ablation',
            'Laser blended vision',
            'Lateral electrical surface stimulation',
            'LDL apheresis',
            'Leukapheresis',
            'Leukocyte apheresis',
            'LILFU',
            'Liver support systems',
            'Maggot therapy',
            'Maintenance therapy',
            'Malotilate',
            'Management of scoliosis',
            'Management of strabismus',
            'Medical gas therapy',
            'Medical nutrition therapy',
            'Medical procedure',
            'Megavitamin therapy',
            'Micropore particle technology',
            'Management of multiple sclerosis',
            'Multiple sclerosis research',
            'Mydicar',
            'Nasal administration',
            'Nasal spray',
            'Nasogastric intubation',
            'NDR Method',
            'Negative-pressure wound therapy',
            'Nerve induction',
            'Neuroreflexotherapy',
            'Non-contact normothermic wound therapy',
            'Optoelectronic plethysmography',
            'Oral pressure therapy',
            'Oral rehydration therapy',
            'Outpatient parenteral antibiotic therapy',
            'Oxygen therapy',
            'Papworth method',
            'Pastille',
            'Pelvic massage',
            'Pentastarch',
            'Peritoneal dialysis',
            'Photopharmacology',
            'Photopheresis',
            'Photothermal therapy',
            'Pink lady (medicine)',
            'Plasmapheresis',
            'Pneumotherapy',
            'Post-exposure prophylaxis',
            'Poultice',
            'Pre-exposure prophylaxis',
            'Preemptive analgesia',
            'Procaine blockade',
            'Prophylactic cranial irradiation',
            'Prostate steam treatment',
            'Proteases (medical and related uses)',
            'Protein replacement therapy',
            'Pulmonary examination',
            'Pulmonary rehabilitation',
            'Pumpable ice technology',
            'Quaternary prevention',
            'Reflex locomotion',
            'Remission (medicine)',
            'Respimat',
            'Revalenta arabica',
            'Rheopheresis',
            'RICE (medicine)',
            'Salvage therapy',
            'SCAR-Fc',
            'Self-Injurious Behavior Inhibiting System',
            'Self-administration',
            'Semper rehydration solution',
            'Single-port laparoscopy',
            'Skunk oil',
            'Smile surgery',
            'Somnoplasty',
            'Sonodynamic therapy',
            'Stem-cell therapy',
            'Strimvelis',
            'Symptomatic treatment',
            'Tamagozake',
            'Tamponade',
            'Therapeutic effect',
            'Targeted temperature management',
            'Therapeutic irrigation',
            'List of therapies',
            'Thickened fluids',
            'Time delay toxin activation',
            'Tobacco smoke enema',
            'Tolerogenic therapy',
            'Tracheal intubation',
            'Traction splint',
            'Transcranial direct-current stimulation',
            'Transdermal continuous oxygen therapy',
            'Transdermal',
            'Transillumination',
            'Transoral robotic surgery',
            'Treatment of human lice',
            'Tuberculosis management',
            'Ultrasonic drug delivery',
            'Ultrasound-enhanced systemic thrombolysis',
            'Urinary catheterization'
        ];

        foreach ($treatments as $treatment) {
            Treatment::firstOrCreate(['name'=>$treatment]);
        }
    }
}
